[[redirects]]
  from = "https://newsbriefing.everbluesea.org/*"
  to = "https://newsbriefing.giseub12.workers.dev/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/heatwave"
  to = "/heatwave/index.html"
  status = 200
  force = true
